/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Player1;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class Player1AgentGUIImpl extends javax.swing.JFrame implements Player1AgentGUI{
    private Player1Agent myAgent;   

    /**
     * Creates new form TacAgentGUIImpl
     */
    public Player1AgentGUIImpl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        B34 = new javax.swing.JButton();
        BT11 = new javax.swing.JButton();
        BT12 = new javax.swing.JButton();
        BT13 = new javax.swing.JButton();
        BT16 = new javax.swing.JButton();
        BT15 = new javax.swing.JButton();
        BT14 = new javax.swing.JButton();
        BT18 = new javax.swing.JButton();
        BT17 = new javax.swing.JButton();
        BT26 = new javax.swing.JButton();
        BT25 = new javax.swing.JButton();
        BT24 = new javax.swing.JButton();
        BT28 = new javax.swing.JButton();
        BT21 = new javax.swing.JButton();
        BT22 = new javax.swing.JButton();
        BT23 = new javax.swing.JButton();
        BT27 = new javax.swing.JButton();
        BT36 = new javax.swing.JButton();
        BT35 = new javax.swing.JButton();
        BT34 = new javax.swing.JButton();
        BT38 = new javax.swing.JButton();
        BT31 = new javax.swing.JButton();
        BT32 = new javax.swing.JButton();
        BT33 = new javax.swing.JButton();
        BT37 = new javax.swing.JButton();
        BT46 = new javax.swing.JButton();
        BT45 = new javax.swing.JButton();
        BT44 = new javax.swing.JButton();
        BT48 = new javax.swing.JButton();
        BT41 = new javax.swing.JButton();
        BT42 = new javax.swing.JButton();
        BT43 = new javax.swing.JButton();
        BT47 = new javax.swing.JButton();
        BT56 = new javax.swing.JButton();
        BT55 = new javax.swing.JButton();
        BT54 = new javax.swing.JButton();
        BT58 = new javax.swing.JButton();
        BT51 = new javax.swing.JButton();
        BT52 = new javax.swing.JButton();
        BT53 = new javax.swing.JButton();
        BT57 = new javax.swing.JButton();
        BT66 = new javax.swing.JButton();
        BT65 = new javax.swing.JButton();
        BT64 = new javax.swing.JButton();
        BT68 = new javax.swing.JButton();
        BT61 = new javax.swing.JButton();
        BT62 = new javax.swing.JButton();
        BT63 = new javax.swing.JButton();
        BT67 = new javax.swing.JButton();
        BT76 = new javax.swing.JButton();
        BT75 = new javax.swing.JButton();
        BT74 = new javax.swing.JButton();
        BT78 = new javax.swing.JButton();
        BT71 = new javax.swing.JButton();
        BT72 = new javax.swing.JButton();
        BT73 = new javax.swing.JButton();
        BT77 = new javax.swing.JButton();
        BT86 = new javax.swing.JButton();
        BT85 = new javax.swing.JButton();
        BT84 = new javax.swing.JButton();
        BT88 = new javax.swing.JButton();
        BT81 = new javax.swing.JButton();
        BT82 = new javax.swing.JButton();
        BT83 = new javax.swing.JButton();
        BT87 = new javax.swing.JButton();

        B34.setBackground(java.awt.Color.white);
        B34.setForeground(java.awt.Color.white);
        B34.setEnabled(false);
        B34.setName("B33"); // NOI18N
        B34.setPreferredSize(new java.awt.Dimension(33, 33));
        B34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B34ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        BT11.setBackground(new java.awt.Color(255, 255, 255));
        BT11.setForeground(new java.awt.Color(255, 255, 255));
        BT11.setEnabled(false);
        BT11.setName("BT11"); // NOI18N
        BT11.setPreferredSize(new java.awt.Dimension(33, 33));
        BT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT11ActionPerformed(evt);
            }
        });

        BT12.setBackground(java.awt.Color.white);
        BT12.setForeground(java.awt.Color.white);
        BT12.setEnabled(false);
        BT12.setName("BT21"); // NOI18N
        BT12.setPreferredSize(new java.awt.Dimension(33, 33));
        BT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT12ActionPerformed(evt);
            }
        });

        BT13.setBackground(java.awt.Color.white);
        BT13.setForeground(java.awt.Color.white);
        BT13.setEnabled(false);
        BT13.setName("BT31"); // NOI18N
        BT13.setPreferredSize(new java.awt.Dimension(33, 33));
        BT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT13ActionPerformed(evt);
            }
        });

        BT16.setBackground(java.awt.Color.white);
        BT16.setForeground(java.awt.Color.white);
        BT16.setEnabled(false);
        BT16.setName("BT61"); // NOI18N
        BT16.setPreferredSize(new java.awt.Dimension(33, 33));
        BT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT16ActionPerformed(evt);
            }
        });

        BT15.setBackground(java.awt.Color.white);
        BT15.setForeground(java.awt.Color.white);
        BT15.setEnabled(false);
        BT15.setName("BT51"); // NOI18N
        BT15.setPreferredSize(new java.awt.Dimension(33, 33));
        BT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT15ActionPerformed(evt);
            }
        });

        BT14.setBackground(java.awt.Color.white);
        BT14.setForeground(java.awt.Color.white);
        BT14.setEnabled(false);
        BT14.setName("BT41"); // NOI18N
        BT14.setPreferredSize(new java.awt.Dimension(33, 33));
        BT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT14ActionPerformed(evt);
            }
        });

        BT18.setBackground(java.awt.Color.white);
        BT18.setForeground(java.awt.Color.white);
        BT18.setEnabled(false);
        BT18.setName("BT81"); // NOI18N
        BT18.setPreferredSize(new java.awt.Dimension(33, 33));
        BT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT18ActionPerformed(evt);
            }
        });

        BT17.setBackground(java.awt.Color.white);
        BT17.setForeground(java.awt.Color.white);
        BT17.setEnabled(false);
        BT17.setName("BT71"); // NOI18N
        BT17.setPreferredSize(new java.awt.Dimension(33, 33));
        BT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT17ActionPerformed(evt);
            }
        });

        BT26.setBackground(java.awt.Color.white);
        BT26.setForeground(java.awt.Color.white);
        BT26.setEnabled(false);
        BT26.setName("BT62"); // NOI18N
        BT26.setPreferredSize(new java.awt.Dimension(33, 33));
        BT26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT26ActionPerformed(evt);
            }
        });

        BT25.setBackground(java.awt.Color.white);
        BT25.setForeground(java.awt.Color.white);
        BT25.setEnabled(false);
        BT25.setName("BT52"); // NOI18N
        BT25.setPreferredSize(new java.awt.Dimension(33, 33));
        BT25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT25ActionPerformed(evt);
            }
        });

        BT24.setBackground(java.awt.Color.white);
        BT24.setForeground(java.awt.Color.white);
        BT24.setEnabled(false);
        BT24.setName("BT42"); // NOI18N
        BT24.setPreferredSize(new java.awt.Dimension(33, 33));
        BT24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT24ActionPerformed(evt);
            }
        });

        BT28.setBackground(java.awt.Color.white);
        BT28.setForeground(java.awt.Color.white);
        BT28.setEnabled(false);
        BT28.setName("BT82"); // NOI18N
        BT28.setPreferredSize(new java.awt.Dimension(33, 33));
        BT28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT28ActionPerformed(evt);
            }
        });

        BT21.setBackground(new java.awt.Color(255, 255, 255));
        BT21.setForeground(new java.awt.Color(255, 255, 255));
        BT21.setEnabled(false);
        BT21.setName("BT21"); // NOI18N
        BT21.setPreferredSize(new java.awt.Dimension(33, 33));
        BT21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT21ActionPerformed(evt);
            }
        });

        BT22.setBackground(java.awt.Color.white);
        BT22.setForeground(java.awt.Color.white);
        BT22.setEnabled(false);
        BT22.setName("BT22"); // NOI18N
        BT22.setPreferredSize(new java.awt.Dimension(33, 33));
        BT22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT22ActionPerformed(evt);
            }
        });

        BT23.setBackground(java.awt.Color.white);
        BT23.setForeground(java.awt.Color.white);
        BT23.setEnabled(false);
        BT23.setName("BT32"); // NOI18N
        BT23.setPreferredSize(new java.awt.Dimension(33, 33));
        BT23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT23ActionPerformed(evt);
            }
        });

        BT27.setBackground(java.awt.Color.white);
        BT27.setForeground(java.awt.Color.white);
        BT27.setEnabled(false);
        BT27.setName("BT72"); // NOI18N
        BT27.setPreferredSize(new java.awt.Dimension(33, 33));
        BT27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT27ActionPerformed(evt);
            }
        });

        BT36.setBackground(java.awt.Color.white);
        BT36.setForeground(java.awt.Color.white);
        BT36.setEnabled(false);
        BT36.setName("BT63"); // NOI18N
        BT36.setPreferredSize(new java.awt.Dimension(33, 33));
        BT36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT36ActionPerformed(evt);
            }
        });

        BT35.setBackground(java.awt.Color.white);
        BT35.setForeground(java.awt.Color.white);
        BT35.setEnabled(false);
        BT35.setName("BT53"); // NOI18N
        BT35.setPreferredSize(new java.awt.Dimension(33, 33));
        BT35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT35ActionPerformed(evt);
            }
        });

        BT34.setBackground(java.awt.Color.white);
        BT34.setForeground(java.awt.Color.white);
        BT34.setEnabled(false);
        BT34.setName("BT43"); // NOI18N
        BT34.setPreferredSize(new java.awt.Dimension(33, 33));
        BT34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT34ActionPerformed(evt);
            }
        });

        BT38.setBackground(java.awt.Color.white);
        BT38.setForeground(java.awt.Color.white);
        BT38.setEnabled(false);
        BT38.setName("BT83"); // NOI18N
        BT38.setPreferredSize(new java.awt.Dimension(33, 33));
        BT38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT38ActionPerformed(evt);
            }
        });

        BT31.setBackground(new java.awt.Color(255, 255, 255));
        BT31.setForeground(new java.awt.Color(255, 255, 255));
        BT31.setEnabled(false);
        BT31.setName("BT13"); // NOI18N
        BT31.setPreferredSize(new java.awt.Dimension(33, 33));
        BT31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT31ActionPerformed(evt);
            }
        });

        BT32.setBackground(java.awt.Color.white);
        BT32.setForeground(java.awt.Color.white);
        BT32.setEnabled(false);
        BT32.setName("BT23"); // NOI18N
        BT32.setPreferredSize(new java.awt.Dimension(33, 33));
        BT32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT32ActionPerformed(evt);
            }
        });

        BT33.setBackground(java.awt.Color.white);
        BT33.setForeground(java.awt.Color.white);
        BT33.setEnabled(false);
        BT33.setName("BT33"); // NOI18N
        BT33.setPreferredSize(new java.awt.Dimension(33, 33));
        BT33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT33ActionPerformed(evt);
            }
        });

        BT37.setBackground(java.awt.Color.white);
        BT37.setForeground(java.awt.Color.white);
        BT37.setEnabled(false);
        BT37.setName("BT73"); // NOI18N
        BT37.setPreferredSize(new java.awt.Dimension(33, 33));
        BT37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT37ActionPerformed(evt);
            }
        });

        BT46.setBackground(java.awt.Color.white);
        BT46.setForeground(java.awt.Color.white);
        BT46.setEnabled(false);
        BT46.setName("BT64"); // NOI18N
        BT46.setPreferredSize(new java.awt.Dimension(33, 33));
        BT46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT46ActionPerformed(evt);
            }
        });

        BT45.setBackground(java.awt.Color.black);
        BT45.setText("O");
        BT45.setEnabled(false);
        BT45.setName("BT54"); // NOI18N
        BT45.setPreferredSize(new java.awt.Dimension(33, 33));
        BT45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT45ActionPerformed(evt);
            }
        });

        BT44.setBackground(java.awt.Color.red);
        BT44.setForeground(java.awt.Color.white);
        BT44.setText("O");
        BT44.setEnabled(false);
        BT44.setName("BT44"); // NOI18N
        BT44.setPreferredSize(new java.awt.Dimension(33, 33));
        BT44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT44ActionPerformed(evt);
            }
        });

        BT48.setBackground(java.awt.Color.white);
        BT48.setForeground(java.awt.Color.white);
        BT48.setEnabled(false);
        BT48.setName("BT84"); // NOI18N
        BT48.setPreferredSize(new java.awt.Dimension(33, 33));
        BT48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT48ActionPerformed(evt);
            }
        });

        BT41.setBackground(new java.awt.Color(255, 255, 255));
        BT41.setForeground(new java.awt.Color(255, 255, 255));
        BT41.setEnabled(false);
        BT41.setName("BT14"); // NOI18N
        BT41.setPreferredSize(new java.awt.Dimension(33, 33));
        BT41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT41ActionPerformed(evt);
            }
        });

        BT42.setBackground(java.awt.Color.white);
        BT42.setForeground(java.awt.Color.white);
        BT42.setEnabled(false);
        BT42.setName("BT24"); // NOI18N
        BT42.setPreferredSize(new java.awt.Dimension(33, 33));
        BT42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT42ActionPerformed(evt);
            }
        });

        BT43.setBackground(java.awt.Color.white);
        BT43.setForeground(java.awt.Color.white);
        BT43.setEnabled(false);
        BT43.setName("BT34"); // NOI18N
        BT43.setPreferredSize(new java.awt.Dimension(33, 33));
        BT43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT43ActionPerformed(evt);
            }
        });

        BT47.setBackground(java.awt.Color.white);
        BT47.setForeground(java.awt.Color.white);
        BT47.setEnabled(false);
        BT47.setName("BT74"); // NOI18N
        BT47.setPreferredSize(new java.awt.Dimension(33, 33));
        BT47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT47ActionPerformed(evt);
            }
        });

        BT56.setBackground(java.awt.Color.white);
        BT56.setForeground(java.awt.Color.white);
        BT56.setEnabled(false);
        BT56.setName("BT65"); // NOI18N
        BT56.setPreferredSize(new java.awt.Dimension(33, 33));
        BT56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT56ActionPerformed(evt);
            }
        });

        BT55.setBackground(java.awt.Color.red);
        BT55.setForeground(java.awt.Color.white);
        BT55.setText("O");
        BT55.setEnabled(false);
        BT55.setName("BT55"); // NOI18N
        BT55.setPreferredSize(new java.awt.Dimension(33, 33));
        BT55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT55ActionPerformed(evt);
            }
        });

        BT54.setBackground(java.awt.Color.black);
        BT54.setText("O");
        BT54.setEnabled(false);
        BT54.setName("BT45"); // NOI18N
        BT54.setPreferredSize(new java.awt.Dimension(33, 33));
        BT54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT54ActionPerformed(evt);
            }
        });

        BT58.setBackground(java.awt.Color.white);
        BT58.setForeground(java.awt.Color.white);
        BT58.setEnabled(false);
        BT58.setName("BT85"); // NOI18N
        BT58.setPreferredSize(new java.awt.Dimension(33, 33));
        BT58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT58ActionPerformed(evt);
            }
        });

        BT51.setBackground(new java.awt.Color(255, 255, 255));
        BT51.setForeground(new java.awt.Color(255, 255, 255));
        BT51.setEnabled(false);
        BT51.setName("BT15"); // NOI18N
        BT51.setPreferredSize(new java.awt.Dimension(33, 33));
        BT51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT51ActionPerformed(evt);
            }
        });

        BT52.setBackground(java.awt.Color.white);
        BT52.setForeground(java.awt.Color.white);
        BT52.setEnabled(false);
        BT52.setName("BT25"); // NOI18N
        BT52.setPreferredSize(new java.awt.Dimension(33, 33));
        BT52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT52ActionPerformed(evt);
            }
        });

        BT53.setBackground(java.awt.Color.white);
        BT53.setForeground(java.awt.Color.white);
        BT53.setEnabled(false);
        BT53.setName("BT35"); // NOI18N
        BT53.setPreferredSize(new java.awt.Dimension(33, 33));
        BT53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT53ActionPerformed(evt);
            }
        });

        BT57.setBackground(java.awt.Color.white);
        BT57.setForeground(java.awt.Color.white);
        BT57.setEnabled(false);
        BT57.setName("BT75"); // NOI18N
        BT57.setPreferredSize(new java.awt.Dimension(33, 33));
        BT57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT57ActionPerformed(evt);
            }
        });

        BT66.setBackground(java.awt.Color.white);
        BT66.setForeground(java.awt.Color.white);
        BT66.setEnabled(false);
        BT66.setName("BT66"); // NOI18N
        BT66.setPreferredSize(new java.awt.Dimension(33, 33));
        BT66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT66ActionPerformed(evt);
            }
        });

        BT65.setBackground(java.awt.Color.white);
        BT65.setForeground(java.awt.Color.white);
        BT65.setEnabled(false);
        BT65.setName("BT56"); // NOI18N
        BT65.setPreferredSize(new java.awt.Dimension(33, 33));
        BT65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT65ActionPerformed(evt);
            }
        });

        BT64.setBackground(java.awt.Color.white);
        BT64.setForeground(java.awt.Color.white);
        BT64.setEnabled(false);
        BT64.setName("BT46"); // NOI18N
        BT64.setPreferredSize(new java.awt.Dimension(33, 33));
        BT64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT64ActionPerformed(evt);
            }
        });

        BT68.setBackground(java.awt.Color.white);
        BT68.setForeground(java.awt.Color.white);
        BT68.setEnabled(false);
        BT68.setName("BT86"); // NOI18N
        BT68.setPreferredSize(new java.awt.Dimension(33, 33));
        BT68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT68ActionPerformed(evt);
            }
        });

        BT61.setBackground(new java.awt.Color(255, 255, 255));
        BT61.setForeground(new java.awt.Color(255, 255, 255));
        BT61.setEnabled(false);
        BT61.setName("BT16"); // NOI18N
        BT61.setPreferredSize(new java.awt.Dimension(33, 33));
        BT61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT61ActionPerformed(evt);
            }
        });

        BT62.setBackground(java.awt.Color.white);
        BT62.setForeground(java.awt.Color.white);
        BT62.setEnabled(false);
        BT62.setName("BT26"); // NOI18N
        BT62.setPreferredSize(new java.awt.Dimension(33, 33));
        BT62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT62ActionPerformed(evt);
            }
        });

        BT63.setBackground(java.awt.Color.white);
        BT63.setForeground(java.awt.Color.white);
        BT63.setEnabled(false);
        BT63.setName("BT36"); // NOI18N
        BT63.setPreferredSize(new java.awt.Dimension(33, 33));
        BT63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT63ActionPerformed(evt);
            }
        });

        BT67.setBackground(java.awt.Color.white);
        BT67.setForeground(java.awt.Color.white);
        BT67.setEnabled(false);
        BT67.setName("BT76"); // NOI18N
        BT67.setPreferredSize(new java.awt.Dimension(33, 33));
        BT67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT67ActionPerformed(evt);
            }
        });

        BT76.setBackground(java.awt.Color.white);
        BT76.setForeground(java.awt.Color.white);
        BT76.setEnabled(false);
        BT76.setName("BT67"); // NOI18N
        BT76.setPreferredSize(new java.awt.Dimension(33, 33));
        BT76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT76ActionPerformed(evt);
            }
        });

        BT75.setBackground(java.awt.Color.white);
        BT75.setForeground(java.awt.Color.white);
        BT75.setEnabled(false);
        BT75.setName("BT57"); // NOI18N
        BT75.setPreferredSize(new java.awt.Dimension(33, 33));
        BT75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT75ActionPerformed(evt);
            }
        });

        BT74.setBackground(java.awt.Color.white);
        BT74.setForeground(java.awt.Color.white);
        BT74.setEnabled(false);
        BT74.setName("BT47"); // NOI18N
        BT74.setPreferredSize(new java.awt.Dimension(33, 33));
        BT74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT74ActionPerformed(evt);
            }
        });

        BT78.setBackground(java.awt.Color.white);
        BT78.setForeground(java.awt.Color.white);
        BT78.setEnabled(false);
        BT78.setName("BT87"); // NOI18N
        BT78.setPreferredSize(new java.awt.Dimension(33, 33));
        BT78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT78ActionPerformed(evt);
            }
        });

        BT71.setBackground(new java.awt.Color(255, 255, 255));
        BT71.setForeground(new java.awt.Color(255, 255, 255));
        BT71.setEnabled(false);
        BT71.setName("BT17"); // NOI18N
        BT71.setPreferredSize(new java.awt.Dimension(33, 33));
        BT71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT71ActionPerformed(evt);
            }
        });

        BT72.setBackground(java.awt.Color.white);
        BT72.setForeground(java.awt.Color.white);
        BT72.setEnabled(false);
        BT72.setName("BT27"); // NOI18N
        BT72.setPreferredSize(new java.awt.Dimension(33, 33));
        BT72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT72ActionPerformed(evt);
            }
        });

        BT73.setBackground(java.awt.Color.white);
        BT73.setForeground(java.awt.Color.white);
        BT73.setEnabled(false);
        BT73.setName("BT37"); // NOI18N
        BT73.setPreferredSize(new java.awt.Dimension(33, 33));
        BT73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT73ActionPerformed(evt);
            }
        });

        BT77.setBackground(java.awt.Color.white);
        BT77.setForeground(java.awt.Color.white);
        BT77.setEnabled(false);
        BT77.setName("BT77"); // NOI18N
        BT77.setPreferredSize(new java.awt.Dimension(33, 33));
        BT77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT77ActionPerformed(evt);
            }
        });

        BT86.setBackground(java.awt.Color.white);
        BT86.setForeground(java.awt.Color.white);
        BT86.setEnabled(false);
        BT86.setName("BT68"); // NOI18N
        BT86.setPreferredSize(new java.awt.Dimension(33, 33));
        BT86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT86ActionPerformed(evt);
            }
        });

        BT85.setBackground(java.awt.Color.white);
        BT85.setForeground(java.awt.Color.white);
        BT85.setEnabled(false);
        BT85.setName("BT58"); // NOI18N
        BT85.setPreferredSize(new java.awt.Dimension(33, 33));
        BT85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT85ActionPerformed(evt);
            }
        });

        BT84.setBackground(java.awt.Color.white);
        BT84.setForeground(java.awt.Color.white);
        BT84.setEnabled(false);
        BT84.setName("BT48"); // NOI18N
        BT84.setPreferredSize(new java.awt.Dimension(33, 33));
        BT84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT84ActionPerformed(evt);
            }
        });

        BT88.setBackground(java.awt.Color.white);
        BT88.setForeground(java.awt.Color.white);
        BT88.setEnabled(false);
        BT88.setName("BT88"); // NOI18N
        BT88.setPreferredSize(new java.awt.Dimension(33, 33));
        BT88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT88ActionPerformed(evt);
            }
        });

        BT81.setBackground(new java.awt.Color(255, 255, 255));
        BT81.setForeground(new java.awt.Color(255, 255, 255));
        BT81.setEnabled(false);
        BT81.setName("BT18"); // NOI18N
        BT81.setPreferredSize(new java.awt.Dimension(33, 33));
        BT81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT81ActionPerformed(evt);
            }
        });

        BT82.setBackground(java.awt.Color.white);
        BT82.setForeground(java.awt.Color.white);
        BT82.setEnabled(false);
        BT82.setName("BT28"); // NOI18N
        BT82.setPreferredSize(new java.awt.Dimension(33, 33));
        BT82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT82ActionPerformed(evt);
            }
        });

        BT83.setBackground(java.awt.Color.white);
        BT83.setForeground(java.awt.Color.white);
        BT83.setEnabled(false);
        BT83.setName("BT38"); // NOI18N
        BT83.setPreferredSize(new java.awt.Dimension(33, 33));
        BT83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT83ActionPerformed(evt);
            }
        });

        BT87.setBackground(java.awt.Color.white);
        BT87.setForeground(java.awt.Color.white);
        BT87.setEnabled(false);
        BT87.setName("BT78"); // NOI18N
        BT87.setPreferredSize(new java.awt.Dimension(33, 33));
        BT87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT87ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(BT21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addComponent(BT11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BT61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BT81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BT88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT11ActionPerformed
        // TODO add your handling code here:
        btnActionPerformed(BT11);
    }//GEN-LAST:event_BT11ActionPerformed

    private void BT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT12ActionPerformed
        // TODO add your handling code here:
        btnActionPerformed(BT12);
    }//GEN-LAST:event_BT12ActionPerformed

    private void BT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT13ActionPerformed
        // TODO add your handling code here:
        btnActionPerformed(BT13);

    }//GEN-LAST:event_BT13ActionPerformed

    private void B34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B34ActionPerformed
         btnActionPerformed(BT34);
    }//GEN-LAST:event_B34ActionPerformed

    private void BT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT16ActionPerformed
          btnActionPerformed(BT16);
    }//GEN-LAST:event_BT16ActionPerformed

    private void BT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT15ActionPerformed
         btnActionPerformed(BT15);
    }//GEN-LAST:event_BT15ActionPerformed

    private void BT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT14ActionPerformed
          btnActionPerformed(BT14);
    }//GEN-LAST:event_BT14ActionPerformed

    private void BT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT18ActionPerformed
          btnActionPerformed(BT18);
    }//GEN-LAST:event_BT18ActionPerformed

    private void BT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT17ActionPerformed
         btnActionPerformed(BT17);
    }//GEN-LAST:event_BT17ActionPerformed

    private void BT26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT26ActionPerformed
          btnActionPerformed(BT26);
    }//GEN-LAST:event_BT26ActionPerformed

    private void BT25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT25ActionPerformed
          btnActionPerformed(BT25);
    }//GEN-LAST:event_BT25ActionPerformed

    private void BT24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT24ActionPerformed
        btnActionPerformed(BT24);
    }//GEN-LAST:event_BT24ActionPerformed

    private void BT28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT28ActionPerformed
         btnActionPerformed(BT28);
    }//GEN-LAST:event_BT28ActionPerformed

    private void BT21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT21ActionPerformed
          btnActionPerformed(BT21);
    }//GEN-LAST:event_BT21ActionPerformed

    private void BT22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT22ActionPerformed
        btnActionPerformed(BT22);
    }//GEN-LAST:event_BT22ActionPerformed

    private void BT23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT23ActionPerformed
          btnActionPerformed(BT23);
    }//GEN-LAST:event_BT23ActionPerformed

    private void BT27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT27ActionPerformed
         btnActionPerformed(BT27);
    }//GEN-LAST:event_BT27ActionPerformed

    private void BT36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT36ActionPerformed
          btnActionPerformed(BT36);
    }//GEN-LAST:event_BT36ActionPerformed

    private void BT35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT35ActionPerformed
        btnActionPerformed(BT35);
    }//GEN-LAST:event_BT35ActionPerformed

    private void BT34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT34ActionPerformed
        btnActionPerformed(BT34);
    }//GEN-LAST:event_BT34ActionPerformed

    private void BT38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT38ActionPerformed
         btnActionPerformed(BT38);
    }//GEN-LAST:event_BT38ActionPerformed

    private void BT31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT31ActionPerformed
       btnActionPerformed(BT31);
    }//GEN-LAST:event_BT31ActionPerformed

    private void BT32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT32ActionPerformed
         btnActionPerformed(BT32);
    }//GEN-LAST:event_BT32ActionPerformed

    private void BT33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT33ActionPerformed
        btnActionPerformed(BT33);
    }//GEN-LAST:event_BT33ActionPerformed

    private void BT37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT37ActionPerformed
        btnActionPerformed(BT37);
    }//GEN-LAST:event_BT37ActionPerformed

    private void BT46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT46ActionPerformed
      btnActionPerformed(BT46);
    }//GEN-LAST:event_BT46ActionPerformed

    private void BT45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT45ActionPerformed
         btnActionPerformed(BT45);
    }//GEN-LAST:event_BT45ActionPerformed

    private void BT44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT44ActionPerformed
    btnActionPerformed(BT44);
    }//GEN-LAST:event_BT44ActionPerformed

    private void BT48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT48ActionPerformed
        btnActionPerformed(BT48);
    }//GEN-LAST:event_BT48ActionPerformed

    private void BT41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT41ActionPerformed
      btnActionPerformed(BT41);
    }//GEN-LAST:event_BT41ActionPerformed

    private void BT42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT42ActionPerformed
       btnActionPerformed(BT42);
    }//GEN-LAST:event_BT42ActionPerformed

    private void BT43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT43ActionPerformed
      btnActionPerformed(BT43);
    }//GEN-LAST:event_BT43ActionPerformed

    private void BT47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT47ActionPerformed
       btnActionPerformed(BT47);
    }//GEN-LAST:event_BT47ActionPerformed

    private void BT56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT56ActionPerformed
      btnActionPerformed(BT56);
    }//GEN-LAST:event_BT56ActionPerformed

    private void BT55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT55ActionPerformed
btnActionPerformed(BT55);
    }//GEN-LAST:event_BT55ActionPerformed

    private void BT54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT54ActionPerformed
   btnActionPerformed(BT54);
    }//GEN-LAST:event_BT54ActionPerformed

    private void BT58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT58ActionPerformed
       btnActionPerformed(BT58);
    }//GEN-LAST:event_BT58ActionPerformed

    private void BT51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT51ActionPerformed
      btnActionPerformed(BT51);
    }//GEN-LAST:event_BT51ActionPerformed

    private void BT52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT52ActionPerformed
      btnActionPerformed(BT52);
    }//GEN-LAST:event_BT52ActionPerformed

    private void BT53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT53ActionPerformed
     btnActionPerformed(BT53);
    }//GEN-LAST:event_BT53ActionPerformed

    private void BT57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT57ActionPerformed
     btnActionPerformed(BT57);
    }//GEN-LAST:event_BT57ActionPerformed

    private void BT66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT66ActionPerformed
       btnActionPerformed(BT66);
    }//GEN-LAST:event_BT66ActionPerformed

    private void BT65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT65ActionPerformed
       btnActionPerformed(BT65);
    }//GEN-LAST:event_BT65ActionPerformed

    private void BT64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT64ActionPerformed
      btnActionPerformed(BT64);
    }//GEN-LAST:event_BT64ActionPerformed

    private void BT68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT68ActionPerformed
    btnActionPerformed(BT68);
    }//GEN-LAST:event_BT68ActionPerformed

    private void BT61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT61ActionPerformed
       btnActionPerformed(BT61);
    }//GEN-LAST:event_BT61ActionPerformed

    private void BT62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT62ActionPerformed
       btnActionPerformed(BT62);
    }//GEN-LAST:event_BT62ActionPerformed

    private void BT63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT63ActionPerformed
  btnActionPerformed(BT63);
    }//GEN-LAST:event_BT63ActionPerformed

    private void BT67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT67ActionPerformed
    btnActionPerformed(BT67);
    }//GEN-LAST:event_BT67ActionPerformed

    private void BT76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT76ActionPerformed
     btnActionPerformed(BT76);
    }//GEN-LAST:event_BT76ActionPerformed

    private void BT75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT75ActionPerformed
  btnActionPerformed(BT75);
    }//GEN-LAST:event_BT75ActionPerformed

    private void BT74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT74ActionPerformed
      btnActionPerformed(BT74);
    }//GEN-LAST:event_BT74ActionPerformed

    private void BT78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT78ActionPerformed
     btnActionPerformed(BT78);
    }//GEN-LAST:event_BT78ActionPerformed

    private void BT71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT71ActionPerformed
      btnActionPerformed(BT71);
    }//GEN-LAST:event_BT71ActionPerformed

    private void BT72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT72ActionPerformed
  btnActionPerformed(BT72);
    }//GEN-LAST:event_BT72ActionPerformed

    private void BT73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT73ActionPerformed
     btnActionPerformed(BT73);
    }//GEN-LAST:event_BT73ActionPerformed

    private void BT77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT77ActionPerformed
      btnActionPerformed(BT77);
    }//GEN-LAST:event_BT77ActionPerformed

    private void BT86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT86ActionPerformed
    btnActionPerformed(BT86);
    }//GEN-LAST:event_BT86ActionPerformed

    private void BT85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT85ActionPerformed
      btnActionPerformed(BT85);
    }//GEN-LAST:event_BT85ActionPerformed

    private void BT84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT84ActionPerformed
     btnActionPerformed(BT84);
    }//GEN-LAST:event_BT84ActionPerformed

    private void BT88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT88ActionPerformed
     btnActionPerformed(BT88);
    }//GEN-LAST:event_BT88ActionPerformed

    private void BT81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT81ActionPerformed
      btnActionPerformed(BT81);
    }//GEN-LAST:event_BT81ActionPerformed

    private void BT82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT82ActionPerformed
    btnActionPerformed(BT82);
    }//GEN-LAST:event_BT82ActionPerformed

    private void BT83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT83ActionPerformed
     btnActionPerformed(BT83);
    }//GEN-LAST:event_BT83ActionPerformed

    private void BT87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT87ActionPerformed
     btnActionPerformed(BT87);
    }//GEN-LAST:event_BT87ActionPerformed

    private void btnActionPerformed(javax.swing.JButton btn){
        System.out.println("Button Clicked");
        if (btn.isEnabled() && myAgent.isTurn()) {
            btn.setBackground(Color.black);
            deactivateButton();
            myAgent.updateBoard(btn.getName());
            notifyUser(btn.getName()+" is pressed.");
        } 
    }
    
    public void activateButton(){
        for (int i=0; i<64; i++) {
                    getButton(i).setEnabled(true);
              
        }
    }
    
    public void deactivateButton(){
         for (int i=0; i<64; i++) {
                    getButton(i).setEnabled(false);
              
        }

    }
    
    public javax.swing.JButton getButton(int btn){
        javax.swing.JButton b = null;
        switch (btn) {
            case 0: b = BT11; break;
            case 1: b = BT12; break;    
            case 2: b = BT13; break;
            case 3: b = BT14; break;
            case 4: b = BT15; break;    
            case 5: b = BT16; break;
            case 6: b = BT17; break;
            case 7: b = BT18; break;
            case 8: b = BT21; break;
            case 9: b = BT22; break;    
            case 10: b = BT23; break;
            case 11: b = BT24; break;
            case 12: b = BT25; break;    
            case 13: b = BT26; break;
            case 14: b = BT27; break;
            case 15: b = BT28; break;
            case 16: b = BT31; break;
            case 17: b = BT32; break;    
            case 18: b = BT33; break;
            case 19: b = BT34; break;
            case 20: b = BT35; break;    
            case 21: b = BT36; break;
            case 22: b = BT37; break;
            case 23: b = BT38; break;
            case 24: b = BT41; break;
            case 25: b = BT42; break;    
            case 26: b = BT43; break;
            case 27: b = BT44; break;
            case 28: b = BT45; break;    
            case 29: b = BT46; break;
            case 30: b = BT47; break;
            case 31: b = BT48; break;
            case 32: b = BT51; break;
            case 33: b = BT52; break;    
            case 34: b = BT53; break;
            case 35: b = BT54; break;
            case 36: b = BT55; break;    
            case 37: b = BT56; break;
            case 38: b = BT57; break;
            case 39: b = BT58; break;
            case 40: b = BT61; break;
            case 41: b = BT62; break;    
            case 42: b = BT63; break;
            case 43: b = BT64; break;
            case 44: b = BT65; break;    
            case 45: b = BT66; break;
            case 46: b = BT67; break;
            case 47: b = BT68; break;
            case 48: b = BT71; break;
            case 49: b = BT72; break;    
            case 50: b = BT73; break;
            case 51: b = BT74; break;
            case 52: b = BT75; break;    
            case 53: b = BT76; break;
            case 54: b = BT77; break;
            case 55: b = BT78; break;
            case 56: b = BT81; break;
            case 57: b = BT82; break;    
            case 58: b = BT83; break;
            case 59: b = BT84; break;
            case 60: b = BT85; break;    
            case 61: b = BT86; break;
            case 62: b = BT87; break;
            case 63: b = BT88; break;
            
        }
        return b;
    }    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player1AgentGUIImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player1AgentGUIImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player1AgentGUIImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player1AgentGUIImpl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player1AgentGUIImpl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B34;
    private javax.swing.JButton BT11;
    private javax.swing.JButton BT12;
    private javax.swing.JButton BT13;
    private javax.swing.JButton BT14;
    private javax.swing.JButton BT15;
    private javax.swing.JButton BT16;
    private javax.swing.JButton BT17;
    private javax.swing.JButton BT18;
    private javax.swing.JButton BT21;
    private javax.swing.JButton BT22;
    private javax.swing.JButton BT23;
    private javax.swing.JButton BT24;
    private javax.swing.JButton BT25;
    private javax.swing.JButton BT26;
    private javax.swing.JButton BT27;
    private javax.swing.JButton BT28;
    private javax.swing.JButton BT31;
    private javax.swing.JButton BT32;
    private javax.swing.JButton BT33;
    private javax.swing.JButton BT34;
    private javax.swing.JButton BT35;
    private javax.swing.JButton BT36;
    private javax.swing.JButton BT37;
    private javax.swing.JButton BT38;
    private javax.swing.JButton BT41;
    private javax.swing.JButton BT42;
    private javax.swing.JButton BT43;
    private javax.swing.JButton BT44;
    private javax.swing.JButton BT45;
    private javax.swing.JButton BT46;
    private javax.swing.JButton BT47;
    private javax.swing.JButton BT48;
    private javax.swing.JButton BT51;
    private javax.swing.JButton BT52;
    private javax.swing.JButton BT53;
    private javax.swing.JButton BT54;
    private javax.swing.JButton BT55;
    private javax.swing.JButton BT56;
    private javax.swing.JButton BT57;
    private javax.swing.JButton BT58;
    private javax.swing.JButton BT61;
    private javax.swing.JButton BT62;
    private javax.swing.JButton BT63;
    private javax.swing.JButton BT64;
    private javax.swing.JButton BT65;
    private javax.swing.JButton BT66;
    private javax.swing.JButton BT67;
    private javax.swing.JButton BT68;
    private javax.swing.JButton BT71;
    private javax.swing.JButton BT72;
    private javax.swing.JButton BT73;
    private javax.swing.JButton BT74;
    private javax.swing.JButton BT75;
    private javax.swing.JButton BT76;
    private javax.swing.JButton BT77;
    private javax.swing.JButton BT78;
    private javax.swing.JButton BT81;
    private javax.swing.JButton BT82;
    private javax.swing.JButton BT83;
    private javax.swing.JButton BT84;
    private javax.swing.JButton BT85;
    private javax.swing.JButton BT86;
    private javax.swing.JButton BT87;
    private javax.swing.JButton BT88;
    // End of variables declaration//GEN-END:variables
    public void setAgent(Player1Agent a) {   
        myAgent = a;   
        setTitle(myAgent.getName());   
    }   
    
    public void notifyUser(String message) {  
        System.out.println("Tac : "+message);
        //logTA.append(message+"\n");   
    } 
        
}

