/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Player2;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class Player2GUIImplementation extends javax.swing.JFrame implements Player2AgentGUI {
    private Player2Agent myAgent;
    /**
     * Creates new form TicGUIImplementation
     */
    public Player2GUIImplementation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BT11 = new javax.swing.JButton();
        BT12 = new javax.swing.JButton();
        BT13 = new javax.swing.JButton();
        BT14 = new javax.swing.JButton();
        BT15 = new javax.swing.JButton();
        BT16 = new javax.swing.JButton();
        BT17 = new javax.swing.JButton();
        BT18 = new javax.swing.JButton();
        BT21 = new javax.swing.JButton();
        BT22 = new javax.swing.JButton();
        BT23 = new javax.swing.JButton();
        BT24 = new javax.swing.JButton();
        BT25 = new javax.swing.JButton();
        BT26 = new javax.swing.JButton();
        BT27 = new javax.swing.JButton();
        BT28 = new javax.swing.JButton();
        BT31 = new javax.swing.JButton();
        BT32 = new javax.swing.JButton();
        BT33 = new javax.swing.JButton();
        BT34 = new javax.swing.JButton();
        BT35 = new javax.swing.JButton();
        BT36 = new javax.swing.JButton();
        BT37 = new javax.swing.JButton();
        BT38 = new javax.swing.JButton();
        BT41 = new javax.swing.JButton();
        BT42 = new javax.swing.JButton();
        BT43 = new javax.swing.JButton();
        BT44 = new javax.swing.JButton();
        BT45 = new javax.swing.JButton();
        BT46 = new javax.swing.JButton();
        BT47 = new javax.swing.JButton();
        BT48 = new javax.swing.JButton();
        BT51 = new javax.swing.JButton();
        BT52 = new javax.swing.JButton();
        BT53 = new javax.swing.JButton();
        BT54 = new javax.swing.JButton();
        BT55 = new javax.swing.JButton();
        BT56 = new javax.swing.JButton();
        BT57 = new javax.swing.JButton();
        BT58 = new javax.swing.JButton();
        BT61 = new javax.swing.JButton();
        BT62 = new javax.swing.JButton();
        BT63 = new javax.swing.JButton();
        BT64 = new javax.swing.JButton();
        BT65 = new javax.swing.JButton();
        BT66 = new javax.swing.JButton();
        BT67 = new javax.swing.JButton();
        BT68 = new javax.swing.JButton();
        BT71 = new javax.swing.JButton();
        BT72 = new javax.swing.JButton();
        BT73 = new javax.swing.JButton();
        BT74 = new javax.swing.JButton();
        BT75 = new javax.swing.JButton();
        BT76 = new javax.swing.JButton();
        BT77 = new javax.swing.JButton();
        BT78 = new javax.swing.JButton();
        BT81 = new javax.swing.JButton();
        BT82 = new javax.swing.JButton();
        BT83 = new javax.swing.JButton();
        BT84 = new javax.swing.JButton();
        BT85 = new javax.swing.JButton();
        BT86 = new javax.swing.JButton();
        BT87 = new javax.swing.JButton();
        BT88 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        BT11.setBackground(new java.awt.Color(255, 255, 255));
        BT11.setEnabled(false);
        BT11.setName("BT11"); // NOI18N
        BT11.setPreferredSize(new java.awt.Dimension(60, 60));
        BT11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT11ActionPerformed(evt);
            }
        });

        BT12.setBackground(new java.awt.Color(255, 255, 255));
        BT12.setEnabled(false);
        BT12.setName("BT21"); // NOI18N
        BT12.setPreferredSize(new java.awt.Dimension(60, 60));
        BT12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT12ActionPerformed(evt);
            }
        });

        BT13.setBackground(new java.awt.Color(255, 255, 255));
        BT13.setEnabled(false);
        BT13.setName("BT31"); // NOI18N
        BT13.setPreferredSize(new java.awt.Dimension(60, 60));
        BT13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT13ActionPerformed(evt);
            }
        });

        BT14.setBackground(new java.awt.Color(255, 255, 255));
        BT14.setEnabled(false);
        BT14.setName("BT41"); // NOI18N
        BT14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT14ActionPerformed(evt);
            }
        });

        BT15.setBackground(new java.awt.Color(255, 255, 255));
        BT15.setEnabled(false);
        BT15.setName("BT51"); // NOI18N
        BT15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT15ActionPerformed(evt);
            }
        });

        BT16.setBackground(new java.awt.Color(255, 255, 255));
        BT16.setEnabled(false);
        BT16.setName("BT61"); // NOI18N
        BT16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT16ActionPerformed(evt);
            }
        });

        BT17.setBackground(new java.awt.Color(255, 255, 255));
        BT17.setEnabled(false);
        BT17.setName("BT71"); // NOI18N
        BT17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT17ActionPerformed(evt);
            }
        });

        BT18.setBackground(new java.awt.Color(255, 255, 255));
        BT18.setEnabled(false);
        BT18.setName("BT81"); // NOI18N
        BT18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT18ActionPerformed(evt);
            }
        });

        BT21.setBackground(new java.awt.Color(255, 255, 255));
        BT21.setEnabled(false);
        BT21.setName("BT12"); // NOI18N
        BT21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT21ActionPerformed(evt);
            }
        });

        BT22.setBackground(new java.awt.Color(255, 255, 255));
        BT22.setEnabled(false);
        BT22.setName("BT22"); // NOI18N
        BT22.setPreferredSize(new java.awt.Dimension(60, 60));
        BT22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT22ActionPerformed(evt);
            }
        });

        BT23.setBackground(new java.awt.Color(255, 255, 255));
        BT23.setEnabled(false);
        BT23.setName("BT32"); // NOI18N
        BT23.setPreferredSize(new java.awt.Dimension(60, 60));
        BT23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT23ActionPerformed(evt);
            }
        });

        BT24.setBackground(new java.awt.Color(255, 255, 255));
        BT24.setEnabled(false);
        BT24.setName("BT42"); // NOI18N
        BT24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT24ActionPerformed(evt);
            }
        });

        BT25.setBackground(new java.awt.Color(255, 255, 255));
        BT25.setEnabled(false);
        BT25.setName("BT52"); // NOI18N
        BT25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT25ActionPerformed(evt);
            }
        });

        BT26.setBackground(new java.awt.Color(255, 255, 255));
        BT26.setEnabled(false);
        BT26.setName("BT62"); // NOI18N
        BT26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT26ActionPerformed(evt);
            }
        });

        BT27.setBackground(new java.awt.Color(255, 255, 255));
        BT27.setEnabled(false);
        BT27.setName("BT72"); // NOI18N
        BT27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT27ActionPerformed(evt);
            }
        });

        BT28.setBackground(new java.awt.Color(255, 255, 255));
        BT28.setEnabled(false);
        BT28.setName("BT82"); // NOI18N
        BT28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT28ActionPerformed(evt);
            }
        });

        BT31.setBackground(new java.awt.Color(255, 255, 255));
        BT31.setEnabled(false);
        BT31.setName("BT13"); // NOI18N
        BT31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT31ActionPerformed(evt);
            }
        });

        BT32.setBackground(new java.awt.Color(255, 255, 255));
        BT32.setEnabled(false);
        BT32.setName("BT23"); // NOI18N
        BT32.setPreferredSize(new java.awt.Dimension(60, 60));
        BT32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT32ActionPerformed(evt);
            }
        });

        BT33.setBackground(new java.awt.Color(255, 255, 255));
        BT33.setEnabled(false);
        BT33.setName("BT33"); // NOI18N
        BT33.setPreferredSize(new java.awt.Dimension(60, 60));
        BT33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT33ActionPerformed(evt);
            }
        });

        BT34.setBackground(new java.awt.Color(255, 255, 255));
        BT34.setEnabled(false);
        BT34.setName("BT43"); // NOI18N
        BT34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT34ActionPerformed(evt);
            }
        });

        BT35.setBackground(new java.awt.Color(255, 255, 255));
        BT35.setEnabled(false);
        BT35.setName("BT53"); // NOI18N
        BT35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT35ActionPerformed(evt);
            }
        });

        BT36.setBackground(new java.awt.Color(255, 255, 255));
        BT36.setEnabled(false);
        BT36.setName("BT63"); // NOI18N
        BT36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT36ActionPerformed(evt);
            }
        });

        BT37.setBackground(new java.awt.Color(255, 255, 255));
        BT37.setEnabled(false);
        BT37.setName("BT73"); // NOI18N
        BT37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT37ActionPerformed(evt);
            }
        });

        BT38.setBackground(new java.awt.Color(255, 255, 255));
        BT38.setEnabled(false);
        BT38.setName("BT83"); // NOI18N
        BT38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT38ActionPerformed(evt);
            }
        });

        BT41.setBackground(new java.awt.Color(255, 255, 255));
        BT41.setEnabled(false);
        BT41.setName("BT14"); // NOI18N
        BT41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT41ActionPerformed(evt);
            }
        });

        BT42.setBackground(new java.awt.Color(255, 255, 255));
        BT42.setEnabled(false);
        BT42.setName("BT24"); // NOI18N
        BT42.setPreferredSize(new java.awt.Dimension(60, 60));
        BT42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT42ActionPerformed(evt);
            }
        });

        BT43.setBackground(new java.awt.Color(255, 255, 255));
        BT43.setEnabled(false);
        BT43.setName("BT34"); // NOI18N
        BT43.setPreferredSize(new java.awt.Dimension(60, 60));
        BT43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT43ActionPerformed(evt);
            }
        });

        BT44.setBackground(java.awt.Color.red);
        BT44.setForeground(new java.awt.Color(255, 255, 255));
        BT44.setText("O");
        BT44.setEnabled(false);
        BT44.setName("BT44"); // NOI18N
        BT44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT44ActionPerformed(evt);
            }
        });

        BT45.setBackground(java.awt.Color.black);
        BT45.setText("O");
        BT45.setEnabled(false);
        BT45.setName("BT54"); // NOI18N
        BT45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT45ActionPerformed(evt);
            }
        });

        BT46.setBackground(new java.awt.Color(255, 255, 255));
        BT46.setEnabled(false);
        BT46.setName("BT64"); // NOI18N
        BT46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT46ActionPerformed(evt);
            }
        });

        BT47.setBackground(new java.awt.Color(255, 255, 255));
        BT47.setEnabled(false);
        BT47.setName("BT74"); // NOI18N
        BT47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT47ActionPerformed(evt);
            }
        });

        BT48.setBackground(new java.awt.Color(255, 255, 255));
        BT48.setEnabled(false);
        BT48.setName("BT84"); // NOI18N
        BT48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT48ActionPerformed(evt);
            }
        });

        BT51.setBackground(new java.awt.Color(255, 255, 255));
        BT51.setEnabled(false);
        BT51.setName("BT15"); // NOI18N
        BT51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT51ActionPerformed(evt);
            }
        });

        BT52.setBackground(new java.awt.Color(255, 255, 255));
        BT52.setEnabled(false);
        BT52.setName("BT25"); // NOI18N
        BT52.setPreferredSize(new java.awt.Dimension(60, 60));
        BT52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT52ActionPerformed(evt);
            }
        });

        BT53.setBackground(new java.awt.Color(255, 255, 255));
        BT53.setEnabled(false);
        BT53.setName("BT35"); // NOI18N
        BT53.setPreferredSize(new java.awt.Dimension(60, 60));
        BT53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT53ActionPerformed(evt);
            }
        });

        BT54.setBackground(java.awt.Color.black);
        BT54.setText("O");
        BT54.setEnabled(false);
        BT54.setName("BT45"); // NOI18N
        BT54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT54ActionPerformed(evt);
            }
        });

        BT55.setBackground(java.awt.Color.red);
        BT55.setForeground(new java.awt.Color(255, 255, 255));
        BT55.setText("O");
        BT55.setEnabled(false);
        BT55.setName("BT55"); // NOI18N
        BT55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT55ActionPerformed(evt);
            }
        });

        BT56.setBackground(new java.awt.Color(255, 255, 255));
        BT56.setToolTipText("");
        BT56.setEnabled(false);
        BT56.setName("BT65"); // NOI18N
        BT56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT56ActionPerformed(evt);
            }
        });

        BT57.setBackground(new java.awt.Color(255, 255, 255));
        BT57.setEnabled(false);
        BT57.setName("BT75"); // NOI18N
        BT57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT57ActionPerformed(evt);
            }
        });

        BT58.setBackground(new java.awt.Color(255, 255, 255));
        BT58.setEnabled(false);
        BT58.setName("BT85"); // NOI18N
        BT58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT58ActionPerformed(evt);
            }
        });

        BT61.setBackground(new java.awt.Color(255, 255, 255));
        BT61.setEnabled(false);
        BT61.setName("BT16"); // NOI18N
        BT61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT61ActionPerformed(evt);
            }
        });

        BT62.setBackground(new java.awt.Color(255, 255, 255));
        BT62.setEnabled(false);
        BT62.setName("BT26"); // NOI18N
        BT62.setPreferredSize(new java.awt.Dimension(60, 60));
        BT62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT62ActionPerformed(evt);
            }
        });

        BT63.setBackground(new java.awt.Color(255, 255, 255));
        BT63.setEnabled(false);
        BT63.setName("BT36"); // NOI18N
        BT63.setPreferredSize(new java.awt.Dimension(60, 60));
        BT63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT63ActionPerformed(evt);
            }
        });

        BT64.setBackground(new java.awt.Color(255, 255, 255));
        BT64.setEnabled(false);
        BT64.setName("BT46"); // NOI18N
        BT64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT64ActionPerformed(evt);
            }
        });

        BT65.setBackground(new java.awt.Color(255, 255, 255));
        BT65.setEnabled(false);
        BT65.setName("BT56"); // NOI18N
        BT65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT65ActionPerformed(evt);
            }
        });

        BT66.setBackground(new java.awt.Color(255, 255, 255));
        BT66.setEnabled(false);
        BT66.setName("BT66"); // NOI18N
        BT66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT66ActionPerformed(evt);
            }
        });

        BT67.setBackground(new java.awt.Color(255, 255, 255));
        BT67.setEnabled(false);
        BT67.setName("BT76"); // NOI18N
        BT67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT67ActionPerformed(evt);
            }
        });

        BT68.setBackground(new java.awt.Color(255, 255, 255));
        BT68.setEnabled(false);
        BT68.setName("BT86"); // NOI18N
        BT68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT68ActionPerformed(evt);
            }
        });

        BT71.setBackground(new java.awt.Color(255, 255, 255));
        BT71.setEnabled(false);
        BT71.setName("BT17"); // NOI18N
        BT71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT71ActionPerformed(evt);
            }
        });

        BT72.setBackground(new java.awt.Color(255, 255, 255));
        BT72.setEnabled(false);
        BT72.setName("BT27"); // NOI18N
        BT72.setPreferredSize(new java.awt.Dimension(60, 60));
        BT72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT72ActionPerformed(evt);
            }
        });

        BT73.setBackground(new java.awt.Color(255, 255, 255));
        BT73.setEnabled(false);
        BT73.setName("BT37"); // NOI18N
        BT73.setPreferredSize(new java.awt.Dimension(60, 60));
        BT73.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT73ActionPerformed(evt);
            }
        });

        BT74.setBackground(new java.awt.Color(255, 255, 255));
        BT74.setEnabled(false);
        BT74.setName("BT47"); // NOI18N
        BT74.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT74ActionPerformed(evt);
            }
        });

        BT75.setBackground(new java.awt.Color(255, 255, 255));
        BT75.setEnabled(false);
        BT75.setName("BT57"); // NOI18N
        BT75.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT75ActionPerformed(evt);
            }
        });

        BT76.setBackground(new java.awt.Color(255, 255, 255));
        BT76.setEnabled(false);
        BT76.setName("BT67"); // NOI18N
        BT76.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT76ActionPerformed(evt);
            }
        });

        BT77.setBackground(new java.awt.Color(255, 255, 255));
        BT77.setEnabled(false);
        BT77.setName("BT77"); // NOI18N
        BT77.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT77ActionPerformed(evt);
            }
        });

        BT78.setBackground(new java.awt.Color(255, 255, 255));
        BT78.setEnabled(false);
        BT78.setName("BT78"); // NOI18N
        BT78.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT78ActionPerformed(evt);
            }
        });

        BT81.setBackground(new java.awt.Color(255, 255, 255));
        BT81.setEnabled(false);
        BT81.setName("BT18"); // NOI18N
        BT81.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT81ActionPerformed(evt);
            }
        });

        BT82.setBackground(new java.awt.Color(255, 255, 255));
        BT82.setEnabled(false);
        BT82.setName("BT28"); // NOI18N
        BT82.setPreferredSize(new java.awt.Dimension(60, 60));
        BT82.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT82ActionPerformed(evt);
            }
        });

        BT83.setBackground(new java.awt.Color(255, 255, 255));
        BT83.setEnabled(false);
        BT83.setName("BT38"); // NOI18N
        BT83.setPreferredSize(new java.awt.Dimension(60, 60));
        BT83.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT83ActionPerformed(evt);
            }
        });

        BT84.setBackground(new java.awt.Color(255, 255, 255));
        BT84.setEnabled(false);
        BT84.setName("BT48"); // NOI18N
        BT84.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT84ActionPerformed(evt);
            }
        });

        BT85.setBackground(new java.awt.Color(255, 255, 255));
        BT85.setEnabled(false);
        BT85.setName("BT58"); // NOI18N
        BT85.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT85ActionPerformed(evt);
            }
        });

        BT86.setBackground(new java.awt.Color(255, 255, 255));
        BT86.setEnabled(false);
        BT86.setName("BT68"); // NOI18N
        BT86.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT86ActionPerformed(evt);
            }
        });

        BT87.setBackground(new java.awt.Color(255, 255, 255));
        BT87.setEnabled(false);
        BT87.setName("BT78"); // NOI18N
        BT87.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT87ActionPerformed(evt);
            }
        });

        BT88.setBackground(new java.awt.Color(255, 255, 255));
        BT88.setEnabled(false);
        BT88.setName("BT88"); // NOI18N
        BT88.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT88ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(BT51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(BT58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(BT31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BT38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BT21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BT28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BT41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BT48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(BT81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BT88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BT11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BT14, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT15, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT16, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(BT17, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BT18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT24, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT25, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT26, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT27, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT28, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT34, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT35, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT36, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT37, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT38, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT41, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT42, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT43, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT44, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT45, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT46, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT47, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT48, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT51, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT52, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT53, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT54, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT55, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT56, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT57, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT58, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT61, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT62, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT63, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT64, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT65, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT66, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT67, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT68, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT71, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT72, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT73, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT74, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT75, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT76, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT77, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT78, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(BT81, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT82, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT83, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT84, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT85, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT86, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BT87, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BT88, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        BT11.getAccessibleContext().setAccessibleName("Btn11");
        BT12.getAccessibleContext().setAccessibleName("Btn21");
        BT13.getAccessibleContext().setAccessibleName("Btn31");
        BT14.getAccessibleContext().setAccessibleName("Btn41");
        BT15.getAccessibleContext().setAccessibleName("Btn51");
        BT15.getAccessibleContext().setAccessibleDescription("");
        BT16.getAccessibleContext().setAccessibleName("Btn61");
        BT17.getAccessibleContext().setAccessibleName("Btn71");
        BT18.getAccessibleContext().setAccessibleName("Btn81");
        BT18.getAccessibleContext().setAccessibleDescription("");
        BT21.getAccessibleContext().setAccessibleName("Btn12");
        BT22.getAccessibleContext().setAccessibleName("Btn22");
        BT23.getAccessibleContext().setAccessibleName("Btn32");
        BT24.getAccessibleContext().setAccessibleName("Btn42");
        BT25.getAccessibleContext().setAccessibleName("Btn52");
        BT26.getAccessibleContext().setAccessibleName("Btn62");
        BT27.getAccessibleContext().setAccessibleName("Btn72");
        BT28.getAccessibleContext().setAccessibleName("Btn82");
        BT31.getAccessibleContext().setAccessibleName("Btn13");
        BT32.getAccessibleContext().setAccessibleName("Btn23");
        BT33.getAccessibleContext().setAccessibleName("Btn33");
        BT33.getAccessibleContext().setAccessibleDescription("");
        BT34.getAccessibleContext().setAccessibleName("Btn43");
        BT35.getAccessibleContext().setAccessibleName("Btn53");
        BT36.getAccessibleContext().setAccessibleName("Btn63");
        BT37.getAccessibleContext().setAccessibleName("Btn73");
        BT38.getAccessibleContext().setAccessibleName("Btn83");
        BT41.getAccessibleContext().setAccessibleName("Btn14");
        BT42.getAccessibleContext().setAccessibleName("Btn24");
        BT43.getAccessibleContext().setAccessibleName("Btn34");
        BT44.getAccessibleContext().setAccessibleName("Btn44");
        BT45.getAccessibleContext().setAccessibleName("Btn54");
        BT46.getAccessibleContext().setAccessibleName("Btn64");
        BT47.getAccessibleContext().setAccessibleName("Btn74");
        BT48.getAccessibleContext().setAccessibleName("Btn84");
        BT51.getAccessibleContext().setAccessibleName("Btn15");
        BT52.getAccessibleContext().setAccessibleName("Btn25");
        BT53.getAccessibleContext().setAccessibleName("Btn35");
        BT54.getAccessibleContext().setAccessibleName("Btn45");
        BT55.getAccessibleContext().setAccessibleName("Btn55");
        BT56.getAccessibleContext().setAccessibleName("Btn65");
        BT57.getAccessibleContext().setAccessibleName("Btn75");
        BT58.getAccessibleContext().setAccessibleName("Btn85");
        BT61.getAccessibleContext().setAccessibleName("Btn16");
        BT61.getAccessibleContext().setAccessibleDescription("");
        BT62.getAccessibleContext().setAccessibleName("Btn26");
        BT63.getAccessibleContext().setAccessibleName("Btn36");
        BT64.getAccessibleContext().setAccessibleName("Btn46");
        BT65.getAccessibleContext().setAccessibleName("Btn56");
        BT66.getAccessibleContext().setAccessibleName("Btn66");
        BT67.getAccessibleContext().setAccessibleName("Btn76");
        BT68.getAccessibleContext().setAccessibleName("Btn86");
        BT71.getAccessibleContext().setAccessibleName("Btn17");
        BT72.getAccessibleContext().setAccessibleName("Btn27");
        BT73.getAccessibleContext().setAccessibleName("Btn37");
        BT74.getAccessibleContext().setAccessibleName("Btn47");
        BT75.getAccessibleContext().setAccessibleName("Btn57");
        BT76.getAccessibleContext().setAccessibleName("Btn67");
        BT77.getAccessibleContext().setAccessibleName("Btn77");
        BT78.getAccessibleContext().setAccessibleName("Btn87");
        BT81.getAccessibleContext().setAccessibleName("Btn18");
        BT82.getAccessibleContext().setAccessibleName("Btn28");
        BT83.getAccessibleContext().setAccessibleName("Btn38");
        BT84.getAccessibleContext().setAccessibleName("Btn48");
        BT85.getAccessibleContext().setAccessibleName("Btn58");
        BT86.getAccessibleContext().setAccessibleName("Btn68");
        BT87.getAccessibleContext().setAccessibleName("Btn78");
        BT88.getAccessibleContext().setAccessibleName("Btn88");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BT11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT11ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT11);
    }//GEN-LAST:event_BT11ActionPerformed

    private void BT12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT12ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT12);
    }//GEN-LAST:event_BT12ActionPerformed

    private void BT13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT13ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT13);
    }//GEN-LAST:event_BT13ActionPerformed

    private void BT14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT14ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT14);
    }//GEN-LAST:event_BT14ActionPerformed

    private void BT15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT15ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT15);
    }//GEN-LAST:event_BT15ActionPerformed

    private void BT16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT16ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT16);
    }//GEN-LAST:event_BT16ActionPerformed

    private void BT17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT17ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT17);
    }//GEN-LAST:event_BT17ActionPerformed

    private void BT18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT18ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT18);
    }//GEN-LAST:event_BT18ActionPerformed

    private void BT21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT21ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(BT21);
    }//GEN-LAST:event_BT21ActionPerformed

    private void BT22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT22ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT22);
    }//GEN-LAST:event_BT22ActionPerformed

    private void BT23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT23ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT23);
    }//GEN-LAST:event_BT23ActionPerformed

    private void BT24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT24ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT24);
    }//GEN-LAST:event_BT24ActionPerformed

    private void BT25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT25ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT25);
    }//GEN-LAST:event_BT25ActionPerformed

    private void BT26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT26ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT26);
    }//GEN-LAST:event_BT26ActionPerformed

    private void BT27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT27ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT27);
    }//GEN-LAST:event_BT27ActionPerformed

    private void BT28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT28ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT28);
    }//GEN-LAST:event_BT28ActionPerformed

    private void BT31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT31ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT31);
    }//GEN-LAST:event_BT31ActionPerformed

    private void BT32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT32ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT32);
    }//GEN-LAST:event_BT32ActionPerformed

    private void BT33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT33ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT33);
    }//GEN-LAST:event_BT33ActionPerformed

    private void BT34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT34ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT34);
    }//GEN-LAST:event_BT34ActionPerformed

    private void BT35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT35ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT35);
    }//GEN-LAST:event_BT35ActionPerformed

    private void BT36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT36ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT36);
    }//GEN-LAST:event_BT36ActionPerformed

    private void BT37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT37ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT37);
    }//GEN-LAST:event_BT37ActionPerformed

    private void BT38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT38ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT38);
    }//GEN-LAST:event_BT38ActionPerformed

    private void BT41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT41ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT41);
    }//GEN-LAST:event_BT41ActionPerformed

    private void BT42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT42ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT42);
    }//GEN-LAST:event_BT42ActionPerformed

    private void BT43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT43ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT43);
    }//GEN-LAST:event_BT43ActionPerformed

    private void BT44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT44ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT44);
    }//GEN-LAST:event_BT44ActionPerformed

    private void BT45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT45ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT45);
    }//GEN-LAST:event_BT45ActionPerformed

    private void BT46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT46ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT46);
    }//GEN-LAST:event_BT46ActionPerformed

    private void BT47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT47ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT47);
    }//GEN-LAST:event_BT47ActionPerformed

    private void BT48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT48ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT48);
    }//GEN-LAST:event_BT48ActionPerformed

    private void BT51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT51ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT51);
    }//GEN-LAST:event_BT51ActionPerformed

    private void BT52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT52ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT52);
    }//GEN-LAST:event_BT52ActionPerformed

    private void BT53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT53ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT53);
    }//GEN-LAST:event_BT53ActionPerformed

    private void BT54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT54ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT54);
         
    }//GEN-LAST:event_BT54ActionPerformed

    private void BT55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT55ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT55);
    }//GEN-LAST:event_BT55ActionPerformed

    private void BT56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT56ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT56);
    }//GEN-LAST:event_BT56ActionPerformed

    private void BT57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT57ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT57);
    }//GEN-LAST:event_BT57ActionPerformed

    private void BT58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT58ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT58);
    }//GEN-LAST:event_BT58ActionPerformed

    private void BT61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT61ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT61);
    }//GEN-LAST:event_BT61ActionPerformed

    private void BT62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT62ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT62);
    }//GEN-LAST:event_BT62ActionPerformed

    private void BT63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT63ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT63);
    }//GEN-LAST:event_BT63ActionPerformed

    private void BT64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT64ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT64);
    }//GEN-LAST:event_BT64ActionPerformed

    private void BT65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT65ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT65);
    }//GEN-LAST:event_BT65ActionPerformed

    private void BT66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT66ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT66);
    }//GEN-LAST:event_BT66ActionPerformed

    private void BT67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT67ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT67);
    }//GEN-LAST:event_BT67ActionPerformed

    private void BT68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT68ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT68);
    }//GEN-LAST:event_BT68ActionPerformed

    private void BT71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT71ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT71);
    }//GEN-LAST:event_BT71ActionPerformed

    private void BT72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT72ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT72);
    }//GEN-LAST:event_BT72ActionPerformed

    private void BT73ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT73ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT73);
    }//GEN-LAST:event_BT73ActionPerformed

    private void BT74ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT74ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT74);
    }//GEN-LAST:event_BT74ActionPerformed

    private void BT75ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT75ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT75);
    }//GEN-LAST:event_BT75ActionPerformed

    private void BT76ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT76ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT76);
    }//GEN-LAST:event_BT76ActionPerformed

    private void BT77ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT77ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT77);
    }//GEN-LAST:event_BT77ActionPerformed

    private void BT78ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT78ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT78);
    }//GEN-LAST:event_BT78ActionPerformed

    private void BT81ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT81ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT81);
    }//GEN-LAST:event_BT81ActionPerformed

    private void BT82ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT82ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT82);
    }//GEN-LAST:event_BT82ActionPerformed

    private void BT83ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT83ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT83);
    }//GEN-LAST:event_BT83ActionPerformed

    private void BT84ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT84ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT84);
    }//GEN-LAST:event_BT84ActionPerformed

    private void BT85ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT85ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT85);
    }//GEN-LAST:event_BT85ActionPerformed

    private void BT86ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT86ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT86);
    }//GEN-LAST:event_BT86ActionPerformed

    private void BT87ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT87ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT87);
    }//GEN-LAST:event_BT87ActionPerformed

    private void BT88ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT88ActionPerformed
        // TODO add your handling code here:
         BtnActionPerformed(BT88);
    }//GEN-LAST:event_BT88ActionPerformed
    
    void BtnActionPerformed(javax.swing.JButton btn) {
        if (btn.isEnabled() && myAgent.isTurn()) {
            btn.setBackground(Color.black);
            deactivateButton();
            System.out.println(btn.getName());
            int pos = Integer.parseInt(btn.getName().substring(2,btn.getName().length()));
            int column=(pos/10)-1;
            int row=(pos%10)-1;
            String result=(column+1)+""+(row+1)+",";
            boolean validLeft=false;   
            boolean validRight=false;
            boolean validDown=false;
            boolean validUp=false;
       
        //kiri
            try{
            if(myAgent.tictactoe[column-1][row]==1){
                for(int k=column-1;k>0;k--){
                      if(myAgent.tictactoe[k-1][row]==-1){
                        validLeft=true;
                        break;
                      }
                      if(myAgent.tictactoe[k-1][row]==0){
                        break;
                      }
                 }
               
             }
            }
            catch(Exception e){
                
            }
           
             
       //kanan
      
           try{
               if(myAgent.tictactoe[column+1][row]==1){
                for(int k=column+1;k+1<8;k++){
                      if(myAgent.tictactoe[k+1][row]==-1){
                        validRight=true;
                        break;
                      }
                      if(myAgent.tictactoe[k+1][row]==0){
                        break;
                      }
                 }
            
             }
            }
            catch(Exception e){
                
            }
           
         
       //bawah
        try{
           if(myAgent.tictactoe[column][row+1]==1){
                for(int k=row+1;k+1<8;k++){
                      if(myAgent.tictactoe[column][k+1]==-1){
                        validDown=true;
                        break;
                      }
                      if(myAgent.tictactoe[column][k+1]==0){
                        break;
                      }
                 }
             }   
        }
         catch(Exception e){
                
        }
           
         
         
       //atas
       try{
           if(myAgent.tictactoe[column][row-1]==1){
                for(int k=row-1;k>0;k--){
                      if(myAgent.tictactoe[column][k-1]==-1){
                        validUp=true;
                        break;
                      }
                      if(myAgent.tictactoe[column][k-1]==0){
                        break;
                      }
                 }
              }   
        }
         catch(Exception e){
                
        }
         
        
      
      if(validLeft==true){
        
          for(int k=column-1;k>0;k--){
           if(myAgent.tictactoe[k][row]==-1){
                break;
             }
           if(myAgent.tictactoe[k][row]==1){
               
                        String temp=(k+1)+""+(row+1);
                         result=result+temp+",";
                        System.out.println("temp: "+temp);
                        getButton(Integer.parseInt(temp)).setBackground(Color.black);                       
             }
          }
          
      }
      if(validRight==true){
    
          for(int k=column+1;k+1<8;k++){
           if(myAgent.tictactoe[k][row]==-1){
               break;
             }
           if(myAgent.tictactoe[k][row]==1){
                       String temp=(k+1)+""+(row+1);
                       result=result+temp+",";
                        System.out.println("temp: "+temp);
                        getButton(Integer.parseInt(temp)).setBackground(Color.black);         
                        
             }
          }
              
      }
      if(validUp==true){
          
          for(int k=row-1;k>0;k--){
           if(myAgent.tictactoe[column][k]==-1){
                        break;
               }
           if(myAgent.tictactoe[column][k]==1){
                        String temp=(column+1)+""+(k+1);
                        result=result+temp+",";
                        System.out.println("temp: "+temp);
                        getButton(Integer.parseInt(temp)).setBackground(Color.black);                
               }
          }    
      }
      if(validDown==true){
          
          for(int k=row+1;k+1<8;k++){
                   if(myAgent.tictactoe[column][k]==-1){
                         break;
                      }
                    if(myAgent.tictactoe[column][k]==1){
                        String temp=(column+1)+""+(k+1);
                        result=result+temp+",";
                        System.out.println("temp: "+temp);
                        getButton(Integer.parseInt(temp)).setBackground(Color.black);   
                        
                      }
              }
      }
            
            myAgent.updateBoard(result);
            notifyUser(btn.getName()+" is pressed.");
        }         
    }
    
    void validate(int pos){
       int column=(pos/10)-1;
       int row=(pos%10)-1;
       boolean validLeft=false;   
       boolean validRight=false;
       boolean validDown=false;
       boolean validUp=false;
       
        //kiri
            try{
            if(myAgent.tictactoe[column-1][row]==1){
                for(int k=column-1;k>0;k--){
                      if(myAgent.tictactoe[k-1][row]==-1){
                        validLeft=true;
                        break;
                      }
                      if(myAgent.tictactoe[k-1][row]==0){
                        break;
                      }
                 }
               
             }
            }
            catch(Exception e){
                
            }
           
             
       //kanan
      
           try{
               if(myAgent.tictactoe[column+1][row]==1){
                for(int k=column+1;k+1<8;k++){
                      if(myAgent.tictactoe[k+1][row]==-1){
                        validRight=true;
                        break;
                      }
                      if(myAgent.tictactoe[k+1][row]==0){
                        break;
                      }
                 }
            
             }
            }
            catch(Exception e){
                
            }
           
         
       //bawah
        try{
           if(myAgent.tictactoe[column][row+1]==1){
                for(int k=row+1;k+1<8;k++){
                      if(myAgent.tictactoe[column][k+1]==-1){
                        validDown=true;
                        break;
                      }
                      if(myAgent.tictactoe[column][k+1]==0){
                        break;
                      }
                 }
             }   
        }
         catch(Exception e){
                
        }
           
         
         
       //atas
       try{
           if(myAgent.tictactoe[column][row-1]==1){
                for(int k=row-1;k>0;k--){
                      if(myAgent.tictactoe[column][k-1]==-1){
                        validUp=true;
                        break;
                      }
                      if(myAgent.tictactoe[column][k-1]==0){
                        break;
                      }
                 }
              }   
        }
         catch(Exception e){
                
        }
         
        
      
      if(validLeft==true||validRight==true||validUp==true||validDown==true){
             getButton(pos).setEnabled(true); 
              getButton(pos).setText("Move");
      }
      
    }
    
    public void activateButton(){
        for (int i=0; i<88; i++) {
                    if(getButton(i)!=null){
                        int c=(i/10)-1;
                        int r=(i%10)-1;
                        if(myAgent.tictactoe[c][r]==0){
                            validate(i);
                            //getButton(i).setEnabled(true); 
                        }
                     }
                   
        }
    }
    
    public void deactivateButton(){
        for (int i=0; i<88; i++) {
            if(getButton(i)!=null){
                    getButton(i).setEnabled(false);
            }
        }
    }


    public javax.swing.JButton getButton(int btn){
        javax.swing.JButton b = null;
        switch (btn) {
            case 11: b = BT11; break;
            case 12: b = BT12; break;    
            case 13: b = BT13; break;
            case 14: b = BT14; break;
            case 15: b = BT15; break;    
            case 16: b = BT16; break;
            case 17: b = BT17; break;
            case 18: b = BT18; break;
            case 21: b = BT21; break;
            case 22: b = BT22; break;    
            case 23: b = BT23; break;
            case 24: b = BT24; break;
            case 25: b = BT25; break;    
            case 26: b = BT26; break;
            case 27: b = BT27; break;
            case 28: b = BT28; break;
            case 31: b = BT31; break;
            case 32: b = BT32; break;    
            case 33: b = BT33; break;
            case 34: b = BT34; break;
            case 35: b = BT35; break;    
            case 36: b = BT36; break;
            case 37: b = BT37; break;
            case 38: b = BT38; break;
            case 41: b = BT41; break;
            case 42: b = BT42; break;    
            case 43: b = BT43; break;
            case 44: b = BT44; break;
            case 45: b = BT45; break;    
            case 46: b = BT46; break;
            case 47: b = BT47; break;
            case 48: b = BT48; break;
            case 51: b = BT51; break;
            case 52: b = BT52; break;    
            case 53: b = BT53; break;
            case 54: b = BT54; break;
            case 55: b = BT55; break;    
            case 56: b = BT56; break;
            case 57: b = BT57; break;
            case 58: b = BT58; break;
            case 61: b = BT61; break;
            case 62: b = BT62; break;    
            case 63: b = BT63; break;
            case 64: b = BT64; break;
            case 65: b = BT65; break;    
            case 66: b = BT66; break;
            case 67: b = BT67; break;
            case 68: b = BT68; break;
            case 71: b = BT71; break;
            case 72: b = BT72; break;    
            case 73: b = BT73; break;
            case 74: b = BT74; break;
            case 75: b = BT75; break;    
            case 76: b = BT76; break;
            case 77: b = BT77; break;
            case 78: b = BT78; break;
            case 81: b = BT81; break;
            case 82: b = BT82; break;    
            case 83: b = BT83; break;
            case 84: b = BT84; break;
            case 85: b = BT85; break;    
            case 86: b = BT86; break;
            case 87: b = BT87; break;
            case 88: b = BT88; break;
        }
        return b;
    }    
    
    public void setAgent(Player2Agent a) {   
        myAgent = a;   
        setTitle(myAgent.getName());   
    }   
    
    public void notifyUser(String message) {  
        System.out.println("Tic : "+message);
        //logTA.append(message+"\n");   
    } 
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Player2GUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Player2GUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Player2GUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Player2GUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Player2GUIImplementation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT11;
    private javax.swing.JButton BT12;
    private javax.swing.JButton BT13;
    private javax.swing.JButton BT14;
    private javax.swing.JButton BT15;
    private javax.swing.JButton BT16;
    private javax.swing.JButton BT17;
    private javax.swing.JButton BT18;
    private javax.swing.JButton BT21;
    private javax.swing.JButton BT22;
    private javax.swing.JButton BT23;
    private javax.swing.JButton BT24;
    private javax.swing.JButton BT25;
    private javax.swing.JButton BT26;
    private javax.swing.JButton BT27;
    private javax.swing.JButton BT28;
    private javax.swing.JButton BT31;
    private javax.swing.JButton BT32;
    private javax.swing.JButton BT33;
    private javax.swing.JButton BT34;
    private javax.swing.JButton BT35;
    private javax.swing.JButton BT36;
    private javax.swing.JButton BT37;
    private javax.swing.JButton BT38;
    private javax.swing.JButton BT41;
    private javax.swing.JButton BT42;
    private javax.swing.JButton BT43;
    private javax.swing.JButton BT44;
    private javax.swing.JButton BT45;
    private javax.swing.JButton BT46;
    private javax.swing.JButton BT47;
    private javax.swing.JButton BT48;
    private javax.swing.JButton BT51;
    private javax.swing.JButton BT52;
    private javax.swing.JButton BT53;
    private javax.swing.JButton BT54;
    private javax.swing.JButton BT55;
    private javax.swing.JButton BT56;
    private javax.swing.JButton BT57;
    private javax.swing.JButton BT58;
    private javax.swing.JButton BT61;
    private javax.swing.JButton BT62;
    private javax.swing.JButton BT63;
    private javax.swing.JButton BT64;
    private javax.swing.JButton BT65;
    private javax.swing.JButton BT66;
    private javax.swing.JButton BT67;
    private javax.swing.JButton BT68;
    private javax.swing.JButton BT71;
    private javax.swing.JButton BT72;
    private javax.swing.JButton BT73;
    private javax.swing.JButton BT74;
    private javax.swing.JButton BT75;
    private javax.swing.JButton BT76;
    private javax.swing.JButton BT77;
    private javax.swing.JButton BT78;
    private javax.swing.JButton BT81;
    private javax.swing.JButton BT82;
    private javax.swing.JButton BT83;
    private javax.swing.JButton BT84;
    private javax.swing.JButton BT85;
    private javax.swing.JButton BT86;
    private javax.swing.JButton BT87;
    private javax.swing.JButton BT88;
    // End of variables declaration//GEN-END:variables
}
