/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tic;

import java.awt.Color;

/**
 *
 * @author USER
 */
public class TicGUIImplementation extends javax.swing.JFrame implements TicAgentGUI {
    private TicAgent myAgent;
    /**
     * Creates new form TicGUIImplementation
     */
    public TicGUIImplementation() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn11 = new javax.swing.JButton();
        Btn12 = new javax.swing.JButton();
        Btn13 = new javax.swing.JButton();
        Btn21 = new javax.swing.JButton();
        Btn22 = new javax.swing.JButton();
        Btn23 = new javax.swing.JButton();
        Btn31 = new javax.swing.JButton();
        Btn32 = new javax.swing.JButton();
        Btn33 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        Btn11.setBackground(new java.awt.Color(255, 255, 255));
        Btn11.setEnabled(false);
        Btn11.setName("Btn11"); // NOI18N
        Btn11.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn11ActionPerformed(evt);
            }
        });

        Btn12.setBackground(new java.awt.Color(255, 255, 255));
        Btn12.setEnabled(false);
        Btn12.setName("Btn12"); // NOI18N
        Btn12.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn12ActionPerformed(evt);
            }
        });

        Btn13.setBackground(new java.awt.Color(255, 255, 255));
        Btn13.setEnabled(false);
        Btn13.setName("Btn13"); // NOI18N
        Btn13.setPreferredSize(new java.awt.Dimension(60, 60));
        Btn13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn13ActionPerformed(evt);
            }
        });

        Btn21.setBackground(new java.awt.Color(255, 255, 255));
        Btn21.setEnabled(false);
        Btn21.setName("Btn21"); // NOI18N
        Btn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn21ActionPerformed(evt);
            }
        });

        Btn22.setBackground(new java.awt.Color(255, 255, 255));
        Btn22.setEnabled(false);
        Btn22.setName("Btn22"); // NOI18N
        Btn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn22ActionPerformed(evt);
            }
        });

        Btn23.setBackground(new java.awt.Color(255, 255, 255));
        Btn23.setEnabled(false);
        Btn23.setName("Btn23"); // NOI18N
        Btn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn23ActionPerformed(evt);
            }
        });

        Btn31.setBackground(new java.awt.Color(255, 255, 255));
        Btn31.setEnabled(false);
        Btn31.setName("Btn31"); // NOI18N
        Btn31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn31ActionPerformed(evt);
            }
        });

        Btn32.setBackground(new java.awt.Color(255, 255, 255));
        Btn32.setEnabled(false);
        Btn32.setName("Btn32"); // NOI18N
        Btn32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn32ActionPerformed(evt);
            }
        });

        Btn33.setBackground(new java.awt.Color(255, 255, 255));
        Btn33.setEnabled(false);
        Btn33.setName("Btn33"); // NOI18N
        Btn33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn33ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn11, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn12, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn13, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn21, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn22, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn23, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btn31, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn32, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Btn33, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        Btn11.getAccessibleContext().setAccessibleName("Btn11");
        Btn12.getAccessibleContext().setAccessibleName("Btn12");
        Btn13.getAccessibleContext().setAccessibleName("Btn13");
        Btn21.getAccessibleContext().setAccessibleName("Btn21");
        Btn22.getAccessibleContext().setAccessibleName("Btn22");
        Btn23.getAccessibleContext().setAccessibleName("Btn23");
        Btn31.getAccessibleContext().setAccessibleName("Btn31");
        Btn32.getAccessibleContext().setAccessibleName("Btn32");
        Btn33.getAccessibleContext().setAccessibleName("Btn33");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn11ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn11);
    }//GEN-LAST:event_Btn11ActionPerformed

    private void Btn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn12ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn12);
    }//GEN-LAST:event_Btn12ActionPerformed

    private void Btn13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn13ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn13);
    }//GEN-LAST:event_Btn13ActionPerformed

    private void Btn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn21ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn21);
    }//GEN-LAST:event_Btn21ActionPerformed

    private void Btn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn22ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn22);
    }//GEN-LAST:event_Btn22ActionPerformed

    private void Btn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn23ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn23);
    }//GEN-LAST:event_Btn23ActionPerformed

    private void Btn31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn31ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn31);
    }//GEN-LAST:event_Btn31ActionPerformed

    private void Btn32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn32ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn32);
    }//GEN-LAST:event_Btn32ActionPerformed

    private void Btn33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn33ActionPerformed
        // TODO add your handling code here:
        BtnActionPerformed(Btn33);
    }//GEN-LAST:event_Btn33ActionPerformed
    
    void BtnActionPerformed(javax.swing.JButton btn) {
        if (btn.isEnabled() && myAgent.isTurn()) {
            btn.setBackground(Color.blue);
            deactivateButton();
            myAgent.updateBoard(btn.getName());
            notifyUser(btn.getName()+" is pressed.");
        }         
    }
    
    public void activateButton(){
        for (int i=0; i<3; i++) {
            for (int j=0; j<3;j++) {
                if (myAgent.tictactoe[i][j] == -1) {
                    getButton(i*3+j).setEnabled(true);
                }
            }
        }
    }
    
    public void deactivateButton(){
        for (int i=0; i<3; i++) {
            for (int j=0; j<3;j++) {
                getButton(i*3+j).setEnabled(false);
            }
        }
    }


    public javax.swing.JButton getButton(int btn){
        javax.swing.JButton b = null;
        switch (btn) {
            case 0: b = Btn11; break;
            case 1: b = Btn12; break;    
            case 2: b = Btn13; break;
            case 3: b = Btn21; break;    
            case 4: b = Btn22; break;
            case 5: b = Btn23; break;    
            case 6: b = Btn31; break;
            case 7: b = Btn32; break;    
            case 8: b = Btn33; break;
        }
        return b;
    }    
    
    public void setAgent(TicAgent a) {   
        myAgent = a;   
        setTitle(myAgent.getName());   
    }   
    
    public void notifyUser(String message) {  
        System.out.println("Tic : "+message);
        //logTA.append(message+"\n");   
    } 
    
     /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicGUIImplementation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicGUIImplementation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn11;
    private javax.swing.JButton Btn12;
    private javax.swing.JButton Btn13;
    private javax.swing.JButton Btn21;
    private javax.swing.JButton Btn22;
    private javax.swing.JButton Btn23;
    private javax.swing.JButton Btn31;
    private javax.swing.JButton Btn32;
    private javax.swing.JButton Btn33;
    // End of variables declaration//GEN-END:variables
}
